#!/usr/bin/env node
/**
 * ArcKit PostToolUse (Write|Edit) Hook — Build Provenance Stamping
 *
 * Stamps a "## Build Provenance" block into ArcKit artefact files,
 * complementing — not duplicating — the human-authored footer that the
 * generating command writes ("Generated by:", "AI Model:", etc.). The
 * block carries only fields the model can't authoritatively self-report:
 *
 *   - Build context (recipe, wave, target ID, topic) when the run came
 *     from /arckit:build via .arckit/state.json
 *   - Requested Effort (from command frontmatter)
 *   - Effective Effort (after silent-downgrade for non-Opus models —
 *     computed from the model self-reported in the existing footer)
 *
 * The block is delimited by HTML comments so the hook is idempotent —
 * re-running on the same file replaces the existing block in place rather
 * than appending duplicates.
 *
 * Sources of truth (in order of preference per field):
 *   - Skill:           state.json target.skill (build-harness runs only)
 *   - Build context:   .arckit/state.json (only when run via /arckit:build)
 *   - Effort:          arckit-claude/commands/{name}.md frontmatter
 *   - Model:           "AI Model:" line in the existing footer (model
 *                      self-reports during generation; we trust that)
 *
 * Fields ALREADY in the existing footer (and therefore not stamped here):
 *   - Generated by / Skill name
 *   - Generated on date
 *   - ArcKit Version
 *   - Project name
 *   - AI Model
 *   - Generation Context / Inputs (BR/FR/NFR IDs the model actually used)
 *
 * If you want one of those, parse the existing footer.
 *
 * Guards (exit silently if any fail):
 *   - tool_name not Write or Edit
 *   - file_path not under /projects/
 *   - filename doesn't match ARC-NNN-*-vN.N.md
 *   - file isn't readable / writable
 *
 * Hook Type: PostToolUse
 * Matcher:   Write|Edit
 * Input:     JSON { tool_name, tool_input: { file_path }, cwd }
 * Output:    On successful stamp, a hookSpecificOutput payload with
 *            updatedToolOutput so the model can see what was recorded
 *            (Claude Code v2.1.121+). Silent when no stamp was needed
 *            (e.g. block was null, or content unchanged) so the original
 *            tool output is preserved.
 *
 *            For Write tool calls this hook runs after update-manifest.mjs
 *            and its updatedToolOutput overwrites that hook's. To avoid
 *            losing the manifest signal, we re-surface it here when a
 *            docs/manifest.json file exists at the repo root.
 * Exit:      0 always
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isFile, findRepoRoot, parseHookInput, emitUpdatedToolOutput } from './hook-utils.mjs';
import {
  buildOkfFieldsForArcArtifact,
  mergeOkfFrontmatter,
  parseFrontmatter,
} from './okf-frontmatter.mjs';
import { extractModelFromContent, downgradeEffort } from './provenance-model.mjs';

const PLUGIN_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// ── Provenance block delimiters ────────────────────────────────────────
const PROV_START = '<!-- arckit-provenance:start -->';
const PROV_END = '<!-- arckit-provenance:end -->';

// ── Field readers ──────────────────────────────────────────────────────

// Locate a command's source file.
//
// Core commands sit at <plugin-root>/commands/<name>.md. Overlay commands do
// NOT: in the published arckit-claude layout they are nested under the core
// root (plugins/repo/commands/…, plugins/uk/nhs/commands/…), and in the dev
// tree they live in sibling plugin directories. Only the core path was ever
// checked, so all 105 overlay commands failed to resolve their `effort:` and
// their artefacts silently lost the provenance block.
function findCommandFile(commandName) {
  const core = join(PLUGIN_ROOT, 'commands', `${commandName}.md`);
  if (isFile(core)) return core;

  // Published layout: overlays nested under the core plugin root.
  const nested = join(PLUGIN_ROOT, 'plugins');
  const fromNested = searchForCommand(nested, commandName, 4);
  if (fromNested) return fromNested;

  // Dev layout: sibling plugin directories (plugins/arckit-*/commands/).
  return searchForCommand(dirname(PLUGIN_ROOT), commandName, 2);
}

// Bounded directory walk: overlay trees are shallow, and an unbounded rglob in
// a PostToolUse hook with a 5s timeout is a bad trade.
function searchForCommand(root, commandName, maxDepth) {
  if (maxDepth < 0) return null;
  let entries;
  try {
    entries = readdirSync(root, { withFileTypes: true });
  } catch {
    return null;
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
    const candidate = join(root, entry.name, 'commands', `${commandName}.md`);
    if (isFile(candidate)) return candidate;
    const deeper = searchForCommand(join(root, entry.name), commandName, maxDepth - 1);
    if (deeper) return deeper;
  }
  return null;
}

function readCommandFrontmatter(commandName) {
  if (!commandName) return {};
  const p = findCommandFile(commandName);
  if (!p) return {};
  let content;
  try {
    content = readFileSync(p, 'utf8');
  } catch {
    return {};
  }
  const m = content.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) return {};
  const yaml = m[1];
  const result = {};
  const effort = yaml.match(/^effort:\s*(\S+)/m);
  if (effort) result.effort = effort[1];
  return result;
}

// Detect command from existing footer ("Generated by: ArcKit `/arckit:X` command")
//
// Handles three shapes:
//   /arckit:X              core, and the portable form used in sources
//   /arckit.X              legacy dot form
//   /arckit-<overlay>:X    what PUBLISHED overlay artefacts carry
//
// The third matters: sync-claude-plugin-layout.py and push-extensions.sh
// namespace overlay invocations at publish time, and that rewrite also hits
// template footers. So an artefact generated from a published overlay template
// says `/arckit-repo:repo-audit`, which the original `arckit[:.]` pattern could
// not match — it required `:` or `.` immediately after `arckit`. The command
// then went undetected, its `effort:` was never read, and the provenance block
// was skipped entirely. Source-tree runs were unaffected, which is why no test
// caught it.
function extractCommandFromContent(content) {
  const m = content.match(/Generated by[^`\n]*`\/?arckit(?:-[a-z0-9-]+)?[:.]([a-z0-9-]+)`/i);
  return m ? m[1] : null;
}

function findBuildContext(filePath, repoRoot) {
  if (!repoRoot) return null;
  const m = filePath.match(/\/projects\/([^/]+)\//);
  if (!m) return null;
  const projectDir = m[1];
  const statePath = join(repoRoot, 'projects', projectDir, '.arckit', 'state.json');
  if (!isFile(statePath)) return null;

  let state;
  try {
    state = JSON.parse(readFileSync(statePath, 'utf8'));
  } catch {
    return null;
  }

  // Match by filename basename — state.json paths may be relative or absolute,
  // and may not match repoRoot exactly across symlinks/tmp dirs.
  const wantBase = basename(filePath);
  const targets = state.targets || {};
  for (const [id, t] of Object.entries(targets)) {
    if (!t.path) continue;
    if (basename(t.path) === wantBase) {
      return {
        recipe: state.recipe || null,
        wave: t.wave ?? null,
        target: id,
        skill: t.skill || null,
        topic: t.topic || null,
      };
    }
  }
  return null;
}

// ── Block construction ────────────────────────────────────────────────
//
// The block carries ONLY harness-derived fields that complement the existing
// human-authored footer. We deliberately do NOT restamp Skill, Model,
// Generated-on, ArcKit Version, or Project — those are already in the footer
// and the model self-reports them at generation time.

function buildProvenanceBlock(fields) {
  const {
    effort_requested,
    effort_effective,
    effort_downgraded,
    build,
    timestamp,
  } = fields;

  // Skip the block entirely if there is nothing harness-only to record.
  if (!effort_requested && !build) return null;

  const rows = [];

  if (effort_requested) {
    rows.push(['Requested Effort', `\`${effort_requested}\``]);
    if (effort_effective) {
      rows.push([
        'Effective Effort',
        effort_downgraded
          ? `\`${effort_effective}\` (downgraded from \`${effort_requested}\` — model does not support that level)`
          : `\`${effort_effective}\``,
      ]);
    } else {
      rows.push([
        'Effective Effort',
        '_unknown — model not parsed from existing footer_',
      ]);
    }
  }

  if (build) {
    rows.push(['Build Recipe', build.recipe ? `\`${build.recipe}\`` : '_unknown_']);
    if (build.wave !== null) rows.push(['Build Wave', String(build.wave)]);
    rows.push(['Build Target', `\`${build.target}\``]);
    if (build.topic) rows.push(['Build Topic', build.topic]);
  }

  rows.push(['Stamped at', timestamp]);

  let body = `${PROV_START}\n\n## Build Provenance\n\n_Stamped automatically by the ArcKit plugin's \`provenance-stamp.mjs\` PostToolUse hook. Complements (does not replace) the human-authored footer above. Carries only fields the model can't authoritatively self-report: build context from \`.arckit/state.json\` and effort levels derived from command frontmatter + the silent-downgrade matrix._\n\n| Field | Value |\n|-------|-------|\n`;
  for (const [k, v] of rows) body += `| ${k} | ${v} |\n`;
  body += `\n${PROV_END}\n`;
  return body;
}

// ── File update ────────────────────────────────────────────────────────

function stampFile(filePath, block) {
  let content;
  try {
    content = readFileSync(filePath, 'utf8');
  } catch {
    return false;
  }

  const startIdx = content.indexOf(PROV_START);
  const endIdx = content.indexOf(PROV_END);

  let newContent;
  if (startIdx >= 0 && endIdx > startIdx) {
    // Replace existing block. Trim trailing newline that follows PROV_END.
    const before = content.slice(0, startIdx);
    const afterStart = endIdx + PROV_END.length;
    const after = content.slice(afterStart).replace(/^\n/, '');
    newContent = before + block + (after.length ? '\n' + after : '');
  } else {
    // Append. Ensure single blank line separator.
    if (!content.endsWith('\n')) content += '\n';
    if (!content.endsWith('\n\n')) content += '\n';
    newContent = content + block;
  }

  if (newContent === content) return false;

  try {
    writeFileSync(filePath, newContent);
    return true;
  } catch {
    return false;
  }
}

function isOkfFrontmatterEnabled(repoRoot) {
  const envValue = String(process.env.ARCKIT_OKF_FRONTMATTER || '').trim().toLowerCase();
  if (envValue === '1' || envValue === 'true') return true;
  if (!repoRoot) return false;

  const configPath = join(repoRoot, '.arckit', 'config.json');
  if (!isFile(configPath)) return false;

  try {
    const config = JSON.parse(readFileSync(configPath, 'utf8'));
    return config.okfFrontmatter === true;
  } catch {
    return false;
  }
}

function toPosix(path) {
  return path.split(/[\\/]/).join('/');
}

function stampOkfFrontmatter(filePath, repoRoot) {
  let content;
  try {
    content = readFileSync(filePath, 'utf8');
  } catch {
    return false;
  }

  const parsed = parseFrontmatter(content);
  const existingTimestamp =
    parsed.hasFrontmatter && !parsed.error && parsed.data.timestamp
      ? parsed.data.timestamp
      : new Date().toISOString();
  const resource = repoRoot ? toPosix(relative(repoRoot, filePath)) : filePath;
  const fields = buildOkfFieldsForArcArtifact({
    filePath,
    content,
    resource,
    timestamp: existingTimestamp,
  });
  if (!fields) return false;

  const updated = mergeOkfFrontmatter(content, fields);
  if (updated === content) return false;

  try {
    writeFileSync(filePath, updated);
    return true;
  } catch {
    return false;
  }
}

// ── Main ──────────────────────────────────────────────────────────────

const data = parseHookInput();
const tool = data.tool_name;
if (tool !== 'Write' && tool !== 'Edit') process.exit(0);

const filePath = data.tool_input?.file_path;
if (!filePath) process.exit(0);
if (!filePath.includes('/projects/')) process.exit(0);

const fname = basename(filePath);
if (!/^ARC-\d{3}-.+-v\d+(\.\d+)?\.md$/.test(fname)) process.exit(0);
if (!isFile(filePath)) process.exit(0);

const repoRoot = findRepoRoot(data.cwd) || dirname(filePath);

let content;
try {
  content = readFileSync(filePath, 'utf8');
} catch {
  process.exit(0);
}

// Resolve fields
const build = findBuildContext(filePath, repoRoot);
const command = extractCommandFromContent(content);
const fm = command ? readCommandFrontmatter(command) : {};
const model = extractModelFromContent(content);

const effortRequested = fm.effort || null;
const effortEffective = downgradeEffort(effortRequested, model);
const effortDowngraded =
  effortEffective !== null && effortRequested !== null && effortEffective !== effortRequested;

const block = buildProvenanceBlock({
  effort_requested: effortRequested,
  effort_effective: effortEffective,
  effort_downgraded: effortDowngraded,
  build,
  timestamp: new Date().toISOString(),
});

const stamped = block !== null && stampFile(filePath, block);
const okfStamped = isOkfFrontmatterEnabled(repoRoot) && stampOkfFrontmatter(filePath, repoRoot);

// Emit hookSpecificOutput.updatedToolOutput so the model sees what the hook
// did. Silent when nothing changed so the original tool output is preserved.
if (stamped || okfStamped) {
  const verb = tool === 'Edit' ? 'edited' : 'written';
  const lines = [`File ${verb}: ${filePath}`];

  if (stamped) {
    // Effort signal — what the model knows it asked for vs what was applied.
    if (effortRequested && effortEffective) {
      const effortMsg = effortDowngraded
        ? `effort: requested=${effortRequested}, effective=${effortEffective} (downgraded — model does not support that level)`
        : `effort: requested=${effortRequested}, effective=${effortEffective}`;
      lines.push(`[ArcKit] provenance stamped (${effortMsg})`);
    } else if (build) {
      lines.push(`[ArcKit] provenance stamped (build: ${build.recipe || '?'}/${build.target})`);
    } else {
      lines.push(`[ArcKit] provenance stamped`);
    }
  }

  if (okfStamped) {
    lines.push(`[ArcKit] OKF frontmatter stamped`);
  }

  // Re-surface the update-manifest signal on Write — that hook ran first
  // and its updatedToolOutput is overwritten by ours. Re-check the same
  // precondition (manifest file exists) so we only mention it when relevant.
  if (tool === 'Write' && repoRoot) {
    const manifestPath = join(repoRoot, 'docs', 'manifest.json');
    if (isFile(manifestPath)) {
      lines.push(`[ArcKit] docs/manifest.json auto-updated`);
    }
  }

  emitUpdatedToolOutput(lines.join('\n'));
}

process.exit(0);
